apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: api-test
  description: Servicio backend
  links:
    - url: https://test.com
      title: Backend Prod
      icon: dashboard
  tags:
    - nodejs
  annotations:
    sonarqube.org/project-key: 'Sonar/com.insignias.backend'
spec:
  type: service
  lifecycle: production
  owner: sebastianacevedo91
  system: test
  dependsOn:
    - Component:front-test
    - Resource:bd-postgres
---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: bd-postgres
  description: Base de datos PostgreSQL de test.
spec:
  type: bd-postgres
  owner: sebastianacevedo91
  system: test
